name: CI

on:
  push:
    branches: [main]
    paths-ignore:
      - '**.md'
      - '.vscode/**'
  pull_request:
    branches: [main]
    paths-ignore:
      - '**.md'
      - '.vscode/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

permissions:
  contents: read

jobs:
  build-and-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - uses: pnpm/setup@v3
        with:
          cache: true
          require-lockfile: true

      - run: pnpm lint
      - run: pnpm check
      - run: pnpm build

        env:
          PUBLIC_APP_URL: https://yaxa.vercel.app
          BETTER_AUTH_SECRET: ci-dummy-secret-key-123456789-production
          BETTER_AUTH_URL: https://yaxa.vercel.app
